#!/bin/bash
# =============================================================================
# Forensight - Log Source Setup Script
# Configures rsyslog and auditd on the source machine to forward logs
# to the Forensight monitoring server.
# =============================================================================

set -e

# ── Configuration ─────────────────────────────────────────────────────────────
FORENSIGHT_SERVER="10.86.160.1"   # Change this to your server IP
FORENSIGHT_PORT="5140"
RSYSLOG_CONF="/etc/rsyslog.d/50-forensight.conf"
AUDIT_RULES="/etc/audit/rules.d/forensight.rules"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' 

# ── Helpers ───────────────────────────────────────────────────────────────────
info()    { echo -e "${BLUE}[*]${NC} $1"; }
success() { echo -e "${GREEN}[✓]${NC} $1"; }
warning() { echo -e "${YELLOW}[!]${NC} $1"; }
error()   { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root. Use: sudo $0"
fi

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       Forensight Setup Script            ║${NC}"
echo -e "${BLUE}║ Log Source Configuration (rsyslog+auditd)║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""

# =============================================================================
# SECTION 1: RSYSLOG
# =============================================================================
info "Checking rsyslog..."

# Check if installed
if ! command -v rsyslogd &>/dev/null; then
    warning "rsyslog not found. Installing..."
    apt-get update -qq
    apt-get install -y rsyslog
    success "rsyslog installed"
else
    success "rsyslog is already installed"
fi

# Check if running
if ! systemctl is-active --quiet rsyslog; then
    warning "rsyslog is not running. Starting..."
    systemctl enable rsyslog
    systemctl start rsyslog
    success "rsyslog started"
else
    success "rsyslog is running"
fi

# Write rsyslog forwarding config
info "Configuring rsyslog forwarding to ${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}..."

cat > "$RSYSLOG_CONF" <<EOF
# ── Forensight Log Forwarding Configuration ──────────────────────────────────
# Forwards security-relevant logs to the Forensight monitoring server
# Generated by forensight-setup.sh

# Forward SSH and authentication logs
auth.*;authpriv.*                       @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}

# Forward sudo logs
if \$programname == 'sudo' then         @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}

# Forward auditd logs
if \$programname == 'audispd' or \$programname == 'audit' then @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}

# Forward su logs
if \$programname == 'su' then           @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}
EOF

success "rsyslog config written to $RSYSLOG_CONF"

# Validate rsyslog config
info "Validating rsyslog configuration..."
if rsyslogd -N1 &>/dev/null; then
    success "rsyslog configuration is valid"
else
    error "rsyslog configuration has errors. Check $RSYSLOG_CONF"
fi

# Restart rsyslog
info "Restarting rsyslog..."
systemctl restart rsyslog
sleep 2

if systemctl is-active --quiet rsyslog; then
    success "rsyslog restarted successfully"
else
    error "rsyslog failed to restart. Run: journalctl -u rsyslog"
fi

# =============================================================================
# SECTION 2: AUDITD
# =============================================================================
echo ""
info "Checking auditd..."

# Check if installed
if ! command -v auditctl &>/dev/null; then
    warning "auditd not found. Installing..."
    apt-get update -qq
    apt-get install -y auditd
    success "auditd installed"
else
    success "auditd is already installed"
fi

# Check if running
if ! systemctl is-active --quiet auditd; then
    warning "auditd is not running. Starting..."
    systemctl enable auditd
    systemctl start auditd
    success "auditd started"
else
    success "auditd is running"
fi

# Write audit rules
info "Writing audit rules to $AUDIT_RULES..."

cat > "$AUDIT_RULES" <<EOF
# ── Forensight Audit Rules ────────────────────────────────────────────────────
# Generated by forensight-setup.sh

# ── Sensitive file monitoring ─────────────────────────────────────────────────
-w /etc/passwd -p wa -k passwd_changes
-w /etc/shadow -p rwa -k shadow_changes
-w /etc/sudoers -p wa -k sudoers_changes
-w /etc/sudoers.d -p wa -k sudoers_changes
-w /etc/ssh/sshd_config -p wa -k sshd_config_changes
-w /root -p rwxa -k root_access

# ── User management binaries ──────────────────────────────────────────────────
-w /usr/sbin/useradd -p x -k user_creation
-w /usr/sbin/userdel -p x -k user_deletion
-w /usr/sbin/usermod -p x -k user_modification
-w /usr/bin/passwd -p x -k password_change

# ── Unauthorized file access attempts (system-wide) ───────────────────────────
-a always,exit -F arch=b64 -S open -F exit=-EACCES -k unauthorized_access
-a always,exit -F arch=b64 -S open -F exit=-EPERM -k unauthorized_access
-a always,exit -F arch=b64 -S openat -F exit=-EACCES -k unauthorized_access
-a always,exit -F arch=b64 -S openat -F exit=-EPERM -k unauthorized_access
EOF

success "Audit rules written to $AUDIT_RULES"

# Load the rules
info "Loading audit rules..."
augenrules --load &>/dev/null || auditctl -R "$AUDIT_RULES"
success "Audit rules loaded"

# Restart auditd
info "Restarting auditd..."
systemctl restart auditd
sleep 2

if systemctl is-active --quiet auditd; then
    success "auditd restarted successfully"
else
    error "auditd failed to restart. Run: journalctl -u auditd"
fi

# Verify rules loaded
RULE_COUNT=$(auditctl -l | wc -l)
success "$RULE_COUNT audit rules active"

# =============================================================================
# SECTION 3: CONNECTIVITY TEST
# =============================================================================
echo ""
info "Testing connectivity to Forensight server ${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}..."

if timeout 3 bash -c "echo > /dev/tcp/${FORENSIGHT_SERVER}/${FORENSIGHT_PORT}" 2>/dev/null; then
    success "Forensight server is reachable on port ${FORENSIGHT_PORT}"
else
    warning "Cannot reach Forensight server on ${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}"
    warning "Make sure the Forensight app is running on the server"
fi

# =============================================================================
# SUMMARY
# =============================================================================
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           Setup Complete!                ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Forwarding logs to: ${BLUE}${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}${NC}"
echo -e "  rsyslog config:     ${BLUE}${RSYSLOG_CONF}${NC}"
echo -e "  Audit rules:        ${BLUE}${AUDIT_RULES}${NC}"
echo ""

