#!/bin/bash
# =============================================================================
# Forensight - Log Source Setup Script
# Configures rsyslog and auditd on the source machine to forward logs
# to the Forensight monitoring server.
# =============================================================================

set -e

# ── Configuration ─────────────────────────────────────────────────────────────
FORENSIGHT_SERVER="10.86.160.1"   # Change this to your server IP
FORENSIGHT_PORT="5140"
RSYSLOG_CONF="/etc/rsyslog.d/50-forensight.conf"
AUDIT_RULES="/etc/audit/rules.d/forensight.rules"
AUDISP_SYSLOG_CONF="/etc/audit/plugins.d/syslog.conf"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ── Helpers ───────────────────────────────────────────────────────────────────
info()    { echo -e "${BLUE}[*]${NC} $1"; }
success() { echo -e "${GREEN}[✓]${NC} $1"; }
warning() { echo -e "${YELLOW}[!]${NC} $1"; }
error()   { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root. Use: sudo $0"
fi

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       Forensight Setup Script            ║${NC}"
echo -e "${BLUE}║ Log Source Configuration (rsyslog+auditd)║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""

# =============================================================================
# SECTION 1: RSYSLOG
# =============================================================================
info "Checking rsyslog..."

if ! command -v rsyslogd &>/dev/null; then
    warning "rsyslog not found. Installing..."
    apt-get update -qq
    apt-get install -y rsyslog
    success "rsyslog installed"
else
    success "rsyslog is already installed"
fi

if ! systemctl is-active --quiet rsyslog; then
    warning "rsyslog is not running. Starting..."
    systemctl enable rsyslog
    systemctl start rsyslog
    success "rsyslog started"
else
    success "rsyslog is running"
fi

info "Configuring rsyslog forwarding to ${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}..."

cat > "$RSYSLOG_CONF" <<EOF
# ── Forensight Log Forwarding Configuration ──────────────────────────────────
# Forwards security-relevant logs to the Forensight monitoring server
# Generated by forensight-setup.sh

# Forward SSH and authentication logs
auth.*;authpriv.*                               @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}

# Forward sudo logs
if \$programname == 'sudo' then                 @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}

# Forward auditd logs via audisp-syslog plugin
if \$programname == 'audisp-syslog' then        @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}

# Forward su logs
if \$programname == 'su' then                   @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}

# Forward iptables port scan logs (kernel messages with PORTSCAN_IN prefix)
if \$msg contains 'PORTSCAN_IN: ' then          @@${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}
EOF

success "rsyslog config written to $RSYSLOG_CONF"

info "Validating rsyslog configuration..."
if rsyslogd -N1 &>/dev/null; then
    success "rsyslog configuration is valid"
else
    error "rsyslog configuration has errors. Check $RSYSLOG_CONF"
fi

info "Restarting rsyslog..."
systemctl restart rsyslog
sleep 2

if systemctl is-active --quiet rsyslog; then
    success "rsyslog restarted successfully"
else
    error "rsyslog failed to restart. Run: journalctl -u rsyslog"
fi

# =============================================================================
# SECTION 2: AUDITD
# =============================================================================
echo ""
info "Checking auditd..."

if ! command -v auditctl &>/dev/null; then
    warning "auditd not found. Installing..."
    apt-get update -qq
    apt-get install -y auditd
    success "auditd installed"
else
    success "auditd is already installed"
fi

if ! systemctl is-active --quiet auditd; then
    warning "auditd is not running. Starting..."
    systemctl enable auditd
    systemctl start auditd
    success "auditd started"
else
    success "auditd is running"
fi

# ── audisp-syslog plugin ───────────────────────────────────────────────────────
info "Checking audisp-syslog plugin..."

if [ -f "$AUDISP_SYSLOG_CONF" ]; then
    if grep -q "active = yes" "$AUDISP_SYSLOG_CONF"; then
        success "audisp-syslog plugin is already enabled"
    else
        warning "audisp-syslog plugin is disabled. Enabling..."
        sed -i 's/active = no/active = yes/' "$AUDISP_SYSLOG_CONF"
        if grep -q "active = yes" "$AUDISP_SYSLOG_CONF"; then
            success "audisp-syslog plugin enabled"
        else
            error "Failed to enable audisp-syslog plugin. Check $AUDISP_SYSLOG_CONF"
        fi
    fi
else
    warning "audisp-syslog config not found at $AUDISP_SYSLOG_CONF"
    ALT_CONF="/etc/audisp/plugins.d/syslog.conf"
    if [ -f "$ALT_CONF" ]; then
        info "Found alternative config at $ALT_CONF. Enabling..."
        sed -i 's/active = no/active = yes/' "$ALT_CONF"
        success "audisp-syslog plugin enabled at $ALT_CONF"
    else
        warning "Could not find audisp-syslog config. Audit forwarding may not work."
    fi
fi

# Write audit rules
info "Writing audit rules to $AUDIT_RULES..."

cat > "$AUDIT_RULES" <<EOF
# ── Forensight Audit Rules ────────────────────────────────────────────────────
# Generated by forensight-setup.sh

# ── Sensitive file monitoring ─────────────────────────────────────────────────
-w /etc/passwd -p wa -k passwd_changes
-w /etc/shadow -p rwa -k shadow_changes
-w /etc/sudoers -p wa -k sudoers_changes
-w /etc/sudoers.d -p wa -k sudoers_changes
-w /etc/ssh/sshd_config -p wa -k sshd_config_changes
-w /root -p rwxa -k root_access

# ── User management binaries ──────────────────────────────────────────────────
-w /usr/sbin/useradd -p x -k user_creation
-w /usr/sbin/userdel -p x -k user_deletion
-w /usr/sbin/usermod -p x -k user_modification
-w /usr/bin/passwd -p x -k password_change

# ── Unauthorized file access attempts (system-wide) ───────────────────────────
-a always,exit -F arch=b64 -S open -F exit=-EACCES -k unauthorized_access
-a always,exit -F arch=b64 -S open -F exit=-EPERM -k unauthorized_access
-a always,exit -F arch=b64 -S openat -F exit=-EACCES -k unauthorized_access
-a always,exit -F arch=b64 -S openat -F exit=-EPERM -k unauthorized_access

# ── Network connection monitoring (outbound) ──────────────────────────────────
-a always,exit -F arch=b64 -S connect -k network_connect
EOF

success "Audit rules written to $AUDIT_RULES"

info "Loading audit rules..."
augenrules --load &>/dev/null || auditctl -R "$AUDIT_RULES"
success "Audit rules loaded"

info "Restarting auditd..."
systemctl restart auditd
sleep 2

if systemctl is-active --quiet auditd; then
    success "auditd restarted successfully"
else
    error "auditd failed to restart. Run: journalctl -u auditd"
fi

RULE_COUNT=$(auditctl -l | wc -l)
success "$RULE_COUNT audit rules active"

# ── Verify audisp-syslog is running ───────────────────────────────────────────
info "Verifying audisp-syslog is running..."
sleep 2
if pgrep -x "audisp-syslog" > /dev/null; then
    success "audisp-syslog process is running"
else
    warning "audisp-syslog process not detected — audit logs may not forward"
    warning "Try running manually: /sbin/audisp-syslog LOG_INFO"
fi

# =============================================================================
# SECTION 3: IPTABLES INBOUND PORT SCAN DETECTION
# =============================================================================
echo ""
info "Configuring iptables inbound port scan logging..."

# Install iptables-persistent to survive reboots
if ! dpkg -l | grep -q iptables-persistent; then
    info "Installing iptables-persistent..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent &>/dev/null
    success "iptables-persistent installed"
fi

# Remove existing Forensight iptables rules to avoid duplicates on re-run
iptables -D INPUT -p tcp --syn -m state --state NEW \
    -m limit --limit 20/s --limit-burst 50 \
    -j LOG --log-prefix "PORTSCAN_IN: " --log-level 4 2>/dev/null || true

iptables -D INPUT -p udp \
    -m limit --limit 20/s --limit-burst 50 \
    -j LOG --log-prefix "PORTSCAN_IN: " --log-level 4 2>/dev/null || true

# Add fresh rules — log new inbound TCP SYN and UDP packets
# Rate limited to avoid log flooding during heavy scans
iptables -A INPUT -p tcp --syn -m state --state NEW \
    -m limit --limit 20/s --limit-burst 50 \
    -j LOG --log-prefix "PORTSCAN_IN: " --log-level 4

iptables -A INPUT -p udp \
    -m limit --limit 20/s --limit-burst 50 \
    -j LOG --log-prefix "PORTSCAN_IN: " --log-level 4

# Persist rules across reboots
netfilter-persistent save &>/dev/null
success "iptables rules added and persisted"

# Verify kernel logging to syslog is enabled
if ! grep -q "PORTSCAN_IN" /etc/rsyslog.d/50-forensight.conf 2>/dev/null; then
    warning "rsyslog may not be forwarding kernel messages — check rsyslog config"
else
    success "rsyslog configured to forward PORTSCAN_IN messages"
fi

# =============================================================================
# SECTION 4: CONNECTIVITY TEST
# =============================================================================
echo ""
info "Testing connectivity to Forensight server ${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}..."

if timeout 3 bash -c "echo > /dev/tcp/${FORENSIGHT_SERVER}/${FORENSIGHT_PORT}" 2>/dev/null; then
    success "Forensight server is reachable on port ${FORENSIGHT_PORT}"
else
    warning "Cannot reach Forensight server on ${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}"
    warning "Make sure the Forensight app is running on the server"
fi

# =============================================================================
# SECTION 5: VERIFICATION
# =============================================================================
echo ""
info "Running verification checks..."

if systemctl is-active --quiet rsyslog; then
    success "rsyslog is active and forwarding"
else
    warning "rsyslog is not running"
fi

if systemctl is-active --quiet auditd; then
    success "auditd is active and monitoring"
else
    warning "auditd is not running"
fi

if grep -q "active = yes" "$AUDISP_SYSLOG_CONF" 2>/dev/null; then
    success "audisp-syslog plugin is enabled"
else
    warning "audisp-syslog plugin may not be enabled"
fi

RULE_COUNT=$(auditctl -l | wc -l)
if [ "$RULE_COUNT" -gt 0 ]; then
    success "$RULE_COUNT audit rules loaded"
else
    warning "No audit rules loaded"
fi

if iptables -L INPUT -n | grep -q "PORTSCAN_IN"; then
    success "iptables port scan logging is active"
else
    warning "iptables port scan rules not found"
fi

# =============================================================================
# SUMMARY
# =============================================================================
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           Setup Complete!                ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Forwarding logs to: ${BLUE}${FORENSIGHT_SERVER}:${FORENSIGHT_PORT}${NC}"
echo -e "  rsyslog config:     ${BLUE}${RSYSLOG_CONF}${NC}"
echo -e "  Audit rules:        ${BLUE}${AUDIT_RULES}${NC}"
echo -e "  audisp-syslog:      ${BLUE}${AUDISP_SYSLOG_CONF}${NC}"
echo -e "  iptables rules:     ${BLUE}active (inbound port scan logging)${NC}"
echo ""
echo -e "  To verify logs are flowing run on the server:"
echo -e "  ${YELLOW}curl http://localhost:5000/api/stats${NC}"
echo ""
